import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:tspendly/features/wallet/models/goal_model.dart';
import 'package:tspendly/features/wallet/providers/goal_form_provider.dart';
import 'package:tspendly/features/wallet/providers/goal_provider.dart';
import 'package:tspendly/features/wallet/widgets/icon_picker_grid.dart';

/// Bottom sheet for creating a new savings goal.
/// Inserts directly into public.goals via the [goalProvider] notifier.
class AddGoal extends ConsumerStatefulWidget {
  const AddGoal({super.key});

  @override
  ConsumerState<AddGoal> createState() => _AddGoalState();
}

class _AddGoalState extends ConsumerState<AddGoal> {
  final _goalNameController = TextEditingController();
  final _targetAmountController = TextEditingController();
  final _deadlineDateController = TextEditingController();
  DateTime? _selectedDate;
  bool _isLoading = false;

  @override
  void dispose() {
    _goalNameController.dispose();
    _targetAmountController.dispose();
    _deadlineDateController.dispose();
    super.dispose();
  }

  Future<void> _selectDate(BuildContext context) async {
    final DateTime? picked = await showDatePicker(
      context: context,
      initialDate: _selectedDate ?? DateTime.now().add(const Duration(days: 30)),
      firstDate: DateTime.now(),
      lastDate: DateTime(2101),
      builder: (context, child) {
        return Theme(
          data: Theme.of(context).copyWith(
            colorScheme: const ColorScheme.light(
              primary: Color(0xFF3B38D0),
              onPrimary: Colors.white,
              onSurface: Colors.black,
            ),
          ),
          child: child!,
        );
      },
    );
    if (picked != null && picked != _selectedDate) {
      setState(() {
        _selectedDate = picked;
        _deadlineDateController.text =
            '${picked.year}-${picked.month.toString().padLeft(2, '0')}-${picked.day.toString().padLeft(2, '0')}';
      });
    }
  }

  Future<void> _submit() async {
    final name = _goalNameController.text.trim();
    final amountText = _targetAmountController.text.trim();

    if (name.isEmpty || amountText.isEmpty) {
      _showError('Please fill in Goal Name and Target Amount.');
      return;
    }

    final targetAmount = double.tryParse(amountText);
    if (targetAmount == null || targetAmount <= 0) {
      _showError('Please enter a valid target amount.');
      return;
    }

    final iconKey =
        ref.read(goalFormProvider).selectedIcon ?? 'savings';

    final newGoal = GoalModel(
      id: '', // will be generated by Supabase
      title: name,
      currentAmount: 0,
      targetAmount: targetAmount,
      icon: iconKey,
      status: 'active',
      deadlineDate: _selectedDate,
    );

    setState(() => _isLoading = true);
    try {
      await ref.read(goalProvider.notifier).addGoal(newGoal);
      if (mounted) Navigator.pop(context);
    } catch (e) {
      if (mounted) _showError('Failed to save goal: $e');
    } finally {
      if (mounted) setState(() => _isLoading = false);
    }
  }

  void _showError(String message) {
    ScaffoldMessenger.of(context).showSnackBar(
      SnackBar(
        content: Text(message),
        backgroundColor: Colors.redAccent,
        behavior: SnackBarBehavior.floating,
        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
      ),
    );
  }

  InputDecoration get _inputDecoration => InputDecoration(
        filled: true,
        fillColor: const Color(0xFFF5F5FA),
        border: OutlineInputBorder(
          borderRadius: BorderRadius.circular(12),
          borderSide: BorderSide.none,
        ),
        contentPadding:
            const EdgeInsets.symmetric(horizontal: 16, vertical: 16),
        hintStyle: const TextStyle(color: Color(0xFFBBBBCC)),
      );

  @override
  Widget build(BuildContext context) {
    final bottomInset = MediaQuery.of(context).viewInsets.bottom;

    return Container(
      padding: EdgeInsets.fromLTRB(24, 0, 24, 24 + bottomInset),
      decoration: const BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.vertical(top: Radius.circular(28)),
      ),
      child: SingleChildScrollView(
        child: Column(
          mainAxisSize: MainAxisSize.min,
          crossAxisAlignment: CrossAxisAlignment.stretch,
          children: [
            // ── Drag handle ──
            const SizedBox(height: 12),
            Center(
              child: Container(
                width: 40,
                height: 4,
                decoration: BoxDecoration(
                  color: Colors.grey[300],
                  borderRadius: BorderRadius.circular(2),
                ),
              ),
            ),
            const SizedBox(height: 20),

            // ── Header ──
            Row(
              mainAxisAlignment: MainAxisAlignment.spaceBetween,
              children: [
                const Text(
                  'Add New Goal',
                  style: TextStyle(
                    fontSize: 22,
                    fontWeight: FontWeight.w800,
                    color: Color(0xFF1A1A2E),
                  ),
                ),
                GestureDetector(
                  onTap: () => Navigator.pop(context),
                  child: Container(
                    width: 36,
                    height: 36,
                    decoration: BoxDecoration(
                      color: const Color(0xFFF5F5FA),
                      borderRadius: BorderRadius.circular(10),
                    ),
                    child: const Icon(
                      Icons.close,
                      color: Color(0xFF4A4A68),
                      size: 18,
                    ),
                  ),
                ),
              ],
            ),
            const SizedBox(height: 24),

            // ── Goal Name ──
            _fieldLabel('Goal Name'),
            const SizedBox(height: 8),
            TextField(
              controller: _goalNameController,
              textCapitalization: TextCapitalization.words,
              decoration: _inputDecoration.copyWith(
                hintText: 'e.g. New Laptop, Vacation',
              ),
            ),
            const SizedBox(height: 20),

            // ── Icon Picker ──
            _fieldLabel('Select Icon'),
            const SizedBox(height: 8),
            const IconPickerGrid(),
            const SizedBox(height: 20),

            // ── Target Amount ──
            _fieldLabel('Target Amount'),
            const SizedBox(height: 8),
            TextField(
              controller: _targetAmountController,
              keyboardType:
                  const TextInputType.numberWithOptions(decimal: true),
              inputFormatters: [
                FilteringTextInputFormatter.allow(RegExp(r'^\d+\.?\d{0,2}')),
              ],
              decoration: _inputDecoration.copyWith(
                hintText: '0.00',
                prefixIcon:
                    const Icon(Icons.attach_money, color: Color(0xFFBBBBCC)),
              ),
            ),
            const SizedBox(height: 20),

            // ── Deadline (optional) ──
            _fieldLabel('Deadline (optional)'),
            const SizedBox(height: 8),
            TextField(
              controller: _deadlineDateController,
              readOnly: true,
              onTap: () => _selectDate(context),
              decoration: _inputDecoration.copyWith(
                hintText: 'Select a date',
                suffixIcon: const Icon(
                  Icons.calendar_today_outlined,
                  color: Color(0xFFBBBBCC),
                ),
              ),
            ),
            const SizedBox(height: 32),

            // ── Submit button ──
            SizedBox(
              height: 54,
              child: ElevatedButton(
                onPressed: _isLoading ? null : _submit,
                style: ElevatedButton.styleFrom(
                  backgroundColor: const Color(0xFF3B38D0),
                  disabledBackgroundColor: const Color(0xFF3B38D0).withOpacity(0.5),
                  shape: RoundedRectangleBorder(
                    borderRadius: BorderRadius.circular(16),
                  ),
                  elevation: 0,
                ),
                child: _isLoading
                    ? const SizedBox(
                        width: 22,
                        height: 22,
                        child: CircularProgressIndicator(
                          color: Colors.white,
                          strokeWidth: 2.5,
                        ),
                      )
                    : const Text(
                        'Save Goal',
                        style: TextStyle(
                          fontSize: 16,
                          fontWeight: FontWeight.w700,
                          color: Colors.white,
                        ),
                      ),
              ),
            ),
          ],
        ),
      ),
    );
  }

  Widget _fieldLabel(String text) => Text(
        text,
        style: const TextStyle(
          fontWeight: FontWeight.w600,
          color: Color(0xFF4A4A68),
          fontSize: 14,
        ),
      );
}
