import 'dart:typed_data';
import 'package:intl/intl.dart';
import 'package:flutter/services.dart' show rootBundle;
import 'package:pdf/widgets.dart' as pw;
import 'package:pdf/pdf.dart';
import 'package:printing/printing.dart';
import 'package:spendly/features/Report/domain/models/live_insights_data.dart';
import 'package:spendly/features/Report/domain/models/generated_report.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:path_provider/path_provider.dart';
import 'dart:io';
import 'package:uuid/uuid.dart';
import 'package:flutter/foundation.dart' show kIsWeb;
import 'dart:convert';
import 'package:spendly/features/Report/domain/models/time_bucket.dart';

enum ReportFrequency { daily, weekly, monthly }

class ReportController {
  // Build a PDF document from the live insights data and selected frequency
  Future<Uint8List> buildPdf(LiveInsightsData data, ReportFrequency freq) async {
    final doc = pw.Document();

    final primary = PdfColor.fromInt(0xFF1A237E);
    final textColor = PdfColor.fromInt(0xFF1A1A1A);

    final title = 'Spendly ${_freqToLabel(freq)} Report';
    final now = DateTime.now();
    final formatter = DateFormat('yyyy-MM-dd HH:mm');

    // Load app logo from assets if available
    pw.MemoryImage? logoImage;
    try {
      final logoData = await rootBundle.load('assets/logo/logo.png');
      logoImage = pw.MemoryImage(logoData.buffer.asUint8List());
    } catch (_) {
      logoImage = null;
    }

    // Build header date range based on frequency
    String rangeLabel;
    DateTime rangeStart;
    DateTime rangeEnd;
    switch (freq) {
      case ReportFrequency.daily:
        rangeStart = DateTime(now.year, now.month, now.day);
        rangeEnd = rangeStart;
        rangeLabel = DateFormat('yyyy-MM-dd').format(rangeStart);
        break;
      case ReportFrequency.weekly:
        // assume week starts 6 days ago
        rangeEnd = now;
        rangeStart = now.subtract(const Duration(days: 6));
        rangeLabel = '${DateFormat('yyyy-MM-dd').format(rangeStart)} → ${DateFormat('yyyy-MM-dd').format(rangeEnd)}';
        break;
      case ReportFrequency.monthly:
      default:
        rangeStart = DateTime(now.year, now.month, 1);
        rangeEnd = DateTime(now.year, now.month + 1, 0);
        rangeLabel = '${DateFormat('yyyy-MM-dd').format(rangeStart)} → ${DateFormat('yyyy-MM-dd').format(rangeEnd)}';
        break;
    }

    doc.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        footer: (context) => pw.Container(
          alignment: pw.Alignment.centerRight,
          margin: const pw.EdgeInsets.only(top: 8.0),
          child: pw.Row(
            mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
            children: [
              pw.Text('Generated by Spendly', style: pw.TextStyle(fontSize: 9, color: textColor)),
              pw.Text('Page ${context.pageNumber} of ${context.pagesCount}', style: pw.TextStyle(fontSize: 9, color: textColor)),
            ],
          ),
        ),
        build: (context) => [
          pw.Container(
            padding: const pw.EdgeInsets.all(12),
            color: PdfColors.white,
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Row(
                  mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                  children: [
                    pw.Row(children: [
                      if (logoImage != null) pw.Image(logoImage, width: 56, height: 56),
                      pw.SizedBox(width: 12),
                      pw.Column(crossAxisAlignment: pw.CrossAxisAlignment.start, children: [
                        pw.Text(title,
                            style: pw.TextStyle(
                                fontSize: 22,
                                color: primary,
                                fontWeight: pw.FontWeight.bold)),
                        pw.SizedBox(height: 4),
                        pw.Text('Insight Report', style: pw.TextStyle(fontSize: 10, color: textColor)),
                      ]),
                    ]),
                    pw.Column(crossAxisAlignment: pw.CrossAxisAlignment.end, children: [
                      pw.Text(formatter.format(now), style: pw.TextStyle(fontSize: 10, color: textColor)),
                      pw.Text(rangeLabel, style: pw.TextStyle(fontSize: 9, color: textColor)),
                    ]),
                  ],
                ),
                pw.SizedBox(height: 12),

                      // Summary
                      pw.Text('Summary',
                        style:
                          pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold)),
                      pw.SizedBox(height: 8),
                      pw.Text(data.summary, style: pw.TextStyle(fontSize: 12)),
                pw.SizedBox(height: 12),

                // Budget status
                pw.Text('Budget Status',
                  style:
                    pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold)),
                pw.SizedBox(height: 6),
                pw.Text(
                  'Current spending: \$${data.currentSpending.toStringAsFixed(2)} / Budget: \$${data.budgetLimit.toStringAsFixed(2)}',
                  style: pw.TextStyle(fontSize: 12)),
                pw.SizedBox(height: 12),

                // Category breakdown table
                pw.Text('Category Breakdown',
                    style:
                        pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold)),
                pw.SizedBox(height: 6),
                if (data.categoryBreakdown.isNotEmpty)
                  pw.Table.fromTextArray(
                    context: context,
                    headers: ['Category', 'Spent', 'Budget'],
                    data: data.categoryBreakdown
                        .map((c) => [
                              c.name,
                              c.amount.toStringAsFixed(2),
                              c.budgetLimit.toStringAsFixed(2)
                            ])
                        .toList(),
                  )
                else
                  pw.Text('No category data available'),

                pw.SizedBox(height: 12),
                // Rich category chart and legend
                if (data.categoryBreakdown.isNotEmpty) ...[
                  pw.Text('Category Chart', style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold)),
                  pw.SizedBox(height: 8),
                  _buildLargeCategoryChart(data),
                  pw.SizedBox(height: 8),
                  _buildCategoryLegend(data),
                ],

                pw.SizedBox(height: 12),

                // Frequency-specific sections
                if (freq == ReportFrequency.daily) ...[
                  pw.Text('Daily Transactions', style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold)),
                  pw.SizedBox(height: 6),
                  _dailyTransactionsTable(context, data, rangeStart),
                ] else if (freq == ReportFrequency.weekly) ...[
                  pw.Text('Weekly Summary', style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold)),
                  pw.SizedBox(height: 6),
                  _timeBucketTable(context, data.weeklyBreakdown),
                ] else ...[
                  pw.Text('Monthly Summary', style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold)),
                  pw.SizedBox(height: 6),
                  _timeBucketTable(context, data.monthlyBreakdown),
                ],

                pw.SizedBox(height: 12),

                // Forecast / predictions (common)
                pw.Text('Forecasts & Predictions', style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold)),
                pw.SizedBox(height: 6),
                pw.Text('Predicted monthly spending: \$${data.monthlyForecast.toStringAsFixed(2)} (trend: ${data.trend})', style: pw.TextStyle(fontSize: 12)),
              ],
            ),
          ),
        ],
      ),
    );

    return doc.save();
  }

  pw.Widget _buildCategoryChart(LiveInsightsData data) {
    final items = data.categoryBreakdown;
    final maxAmount = items.map((e) => e.amount).fold<double>(0.0, (a, b) => a > b ? a : b);
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: items.map((c) {
        final widthFactor = maxAmount <= 0 ? 0.0 : (c.amount / maxAmount);
        return pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Text('${c.name} — \$${c.amount.toStringAsFixed(2)}', style: pw.TextStyle(fontSize: 10)),
              pw.Container(
                height: 10,
                width: 200,
                decoration: pw.BoxDecoration(
                  border: pw.Border.all(color: PdfColors.grey300),
                ),
                child: pw.Row(children: [
                  pw.Container(
                    width: 200 * widthFactor,
                    height: 10,
                    color: PdfColor.fromInt((c.color.value & 0xFFFFFF) | 0xFF000000),
                  )
                ]),
              ),
              pw.SizedBox(height: 6),
            ]);
      }).toList(),
    );
  }

  pw.Widget _buildLargeCategoryChart(LiveInsightsData data) {
    final items = data.categoryBreakdown;
    final maxAmount = items.map((e) => e.amount).fold<double>(0.0, (a, b) => a > b ? a : b);
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: items.map((c) {
        final widthFactor = maxAmount <= 0 ? 0.0 : (c.amount / maxAmount);
        final percent = data.currentSpending <= 0 ? 0.0 : (c.amount / data.currentSpending) * 100;
        return pw.Row(
          crossAxisAlignment: pw.CrossAxisAlignment.center,
          children: [
            pw.Container(width: 90, child: pw.Text(c.name, style: pw.TextStyle(fontSize: 10))),
            pw.SizedBox(width: 8),
            pw.Container(
              width: 300,
              height: 14,
              decoration: pw.BoxDecoration(border: pw.Border.all(color: PdfColors.grey300)),
              child: pw.Stack(children: [
                pw.Positioned(left: 0, top: 0, child: pw.Container(width: 300 * widthFactor, height: 14, color: PdfColor.fromInt((c.color.value & 0xFFFFFF) | 0xFF000000))),
              ]),
            ),
            pw.SizedBox(width: 8),
            pw.Text('${percent.toStringAsFixed(1)}%', style: pw.TextStyle(fontSize: 10)),
          ],
        );
      }).toList(),
    );
  }

  pw.Widget _buildCategoryLegend(LiveInsightsData data) {
    final items = data.categoryBreakdown;
    return pw.Wrap(
      spacing: 8,
      runSpacing: 6,
      children: items.map((c) => pw.Container(padding: const pw.EdgeInsets.all(6), child: pw.Row(children: [
        pw.Container(width: 10, height: 10, color: PdfColor.fromInt((c.color.value & 0xFFFFFF) | 0xFF000000)),
        pw.SizedBox(width: 6),
        pw.Text('${c.name}  ', style: pw.TextStyle(fontSize: 10)),
        pw.Text('\$${c.amount.toStringAsFixed(2)}', style: pw.TextStyle(fontSize: 10, color: PdfColors.grey700)),
      ]))).toList(),
    );
  }

  pw.Widget _dailyTransactionsTable(pw.Context context, LiveInsightsData data, DateTime date) {
    final transactions = data.transactions.where((tx) {
      final d = DateTime(tx.dateTime.year, tx.dateTime.month, tx.dateTime.day);
      return d == DateTime(date.year, date.month, date.day);
    }).toList();

    if (transactions.isEmpty) {
      return pw.Text('No transactions for selected day.');
    }

    final rows = transactions.map((t) => [t.dateTime.toIso8601String(), t.title, '\$${t.amount.toStringAsFixed(2)}', t.category]).toList();

    return pw.Table.fromTextArray(context: context, headers: ['Date', 'Title', 'Amount', 'Category'], data: rows);
  }

  pw.Widget _timeBucketTable(pw.Context context, List<TimeBucket> buckets) {
    if (buckets.isEmpty) return pw.Text('No data available');
    final rows = buckets.map((b) => [b.label ?? '', '\$${b.total.toStringAsFixed(2)}', b.count.toString()]).toList();
    return pw.Table.fromTextArray(context: context, headers: ['Period', 'Total', 'Transactions'], data: rows);
  }

  Future<void> sharePdf(Uint8List bytes, String filename) async {
    await Printing.sharePdf(bytes: bytes, filename: filename);
  }

  /// Save PDF bytes to disk (app documents directory) and record metadata
  Future<GeneratedReport> savePdfAndRecord(Uint8List bytes, ReportFrequency freq) async {
    final now = DateTime.now();
    final filename = 'spendly_${freq.name}_${now.year}${now.month.toString().padLeft(2, '0')}${now.day.toString().padLeft(2, '0')}_${now.hour.toString().padLeft(2,'0')}${now.minute.toString().padLeft(2,'0')}.pdf';

    final prefs = await SharedPreferences.getInstance();

    String path = filename;
    if (kIsWeb) {
      // store bytes as base64 in preferences (web has limited storage)
      final key = 'report_bytes_${const Uuid().v4()}';
      await prefs.setString(key, base64Encode(bytes));
      path = key; // store the key so we can retrieve bytes later
    } else {
      final dir = await getApplicationDocumentsDirectory();
      final file = File('${dir.path}/$filename');
      await file.writeAsBytes(bytes);
      path = file.path;
    }

    final id = const Uuid().v4();
    final record = GeneratedReport(id: id, filename: filename, path: path, frequency: freq.name, createdAt: now);

    final existing = GeneratedReport.listFromJson(prefs.getString('generated_reports'));
    existing.insert(0, record);
    await prefs.setString('generated_reports', GeneratedReport.listToJson(existing));

    return record;
  }

  Future<List<GeneratedReport>> loadSavedReports() async {
    final prefs = await SharedPreferences.getInstance();
    return GeneratedReport.listFromJson(prefs.getString('generated_reports'));
  }

  Future<Uint8List?> loadSavedReportBytes(GeneratedReport report) async {
    if (kIsWeb) {
      final prefs = await SharedPreferences.getInstance();
      final base64Value = prefs.getString(report.path);
      if (base64Value == null) {
        return null;
      }
      return base64Decode(base64Value);
    }

    final file = File(report.path);
    if (!await file.exists()) {
      return null;
    }
    return file.readAsBytes();
  }

  String _freqToLabel(ReportFrequency freq) {
    switch (freq) {
      case ReportFrequency.daily:
        return 'Daily';
      case ReportFrequency.weekly:
        return 'Weekly';
      case ReportFrequency.monthly:
      default:
        return 'Monthly';
    }
  }
}
