/// Complete list of world currencies with country emoji flags.
class CurrencyInfo {
  final String name;
  final String code;
  final String symbol;
  final String flag;

  const CurrencyInfo({
    required this.name,
    required this.code,
    required this.symbol,
    required this.flag,
  });
}

const List<CurrencyInfo> allCurrencies = [
  CurrencyInfo(name: 'Egyptian Pound', code: 'EGP', symbol: 'E£', flag: '🇪🇬'),
  CurrencyInfo(name: 'US Dollar', code: 'USD', symbol: '\$', flag: '🇺🇸'),
  CurrencyInfo(name: 'Euro', code: 'EUR', symbol: '€', flag: '🇪🇺'),
  CurrencyInfo(name: 'British Pound', code: 'GBP', symbol: '£', flag: '🇬🇧'),
  CurrencyInfo(name: 'Saudi Riyal', code: 'SAR', symbol: '﷼', flag: '🇸🇦'),
  CurrencyInfo(name: 'UAE Dirham', code: 'AED', symbol: 'د.إ', flag: '🇦🇪'),
  CurrencyInfo(name: 'Afghan Afghani', code: 'AFN', symbol: '؋', flag: '🇦🇫'),
  CurrencyInfo(name: 'Albanian Lek', code: 'ALL', symbol: 'L', flag: '🇦🇱'),
  CurrencyInfo(name: 'Armenian Dram', code: 'AMD', symbol: '֏', flag: '🇦🇲'),
  CurrencyInfo(name: 'Angolan Kwanza', code: 'AOA', symbol: 'Kz', flag: '🇦🇴'),
  CurrencyInfo(name: 'Argentine Peso', code: 'ARS', symbol: '\$', flag: '🇦🇷'),
  CurrencyInfo(name: 'Australian Dollar', code: 'AUD', symbol: 'A\$', flag: '🇦🇺'),
  CurrencyInfo(name: 'Aruban Florin', code: 'AWG', symbol: 'ƒ', flag: '🇦🇼'),
  CurrencyInfo(name: 'Azerbaijani Manat', code: 'AZN', symbol: '₼', flag: '🇦🇿'),
  CurrencyInfo(name: 'Bosnia Mark', code: 'BAM', symbol: 'KM', flag: '🇧🇦'),
  CurrencyInfo(name: 'Barbadian Dollar', code: 'BBD', symbol: 'Bds\$', flag: '🇧🇧'),
  CurrencyInfo(name: 'Bangladeshi Taka', code: 'BDT', symbol: '৳', flag: '🇧🇩'),
  CurrencyInfo(name: 'Bulgarian Lev', code: 'BGN', symbol: 'лв', flag: '🇧🇬'),
  CurrencyInfo(name: 'Bahraini Dinar', code: 'BHD', symbol: '.د.ب', flag: '🇧🇭'),
  CurrencyInfo(name: 'Burundian Franc', code: 'BIF', symbol: 'FBu', flag: '🇧🇮'),
  CurrencyInfo(name: 'Bermudian Dollar', code: 'BMD', symbol: 'BD\$', flag: '🇧🇲'),
  CurrencyInfo(name: 'Brunei Dollar', code: 'BND', symbol: 'B\$', flag: '🇧🇳'),
  CurrencyInfo(name: 'Bolivian Boliviano', code: 'BOB', symbol: 'Bs.', flag: '🇧🇴'),
  CurrencyInfo(name: 'Brazilian Real', code: 'BRL', symbol: 'R\$', flag: '🇧🇷'),
  CurrencyInfo(name: 'Bahamian Dollar', code: 'BSD', symbol: 'B\$', flag: '🇧🇸'),
  CurrencyInfo(name: 'Bhutanese Ngultrum', code: 'BTN', symbol: 'Nu.', flag: '🇧🇹'),
  CurrencyInfo(name: 'Botswana Pula', code: 'BWP', symbol: 'P', flag: '🇧🇼'),
  CurrencyInfo(name: 'Belarusian Ruble', code: 'BYN', symbol: 'Br', flag: '🇧🇾'),
  CurrencyInfo(name: 'Belize Dollar', code: 'BZD', symbol: 'BZ\$', flag: '🇧🇿'),
  CurrencyInfo(name: 'Canadian Dollar', code: 'CAD', symbol: 'C\$', flag: '🇨🇦'),
  CurrencyInfo(name: 'Congolese Franc', code: 'CDF', symbol: 'FC', flag: '🇨🇩'),
  CurrencyInfo(name: 'Swiss Franc', code: 'CHF', symbol: 'CHF', flag: '🇨🇭'),
  CurrencyInfo(name: 'Chilean Peso', code: 'CLP', symbol: '\$', flag: '🇨🇱'),
  CurrencyInfo(name: 'Chinese Yuan', code: 'CNY', symbol: '¥', flag: '🇨🇳'),
  CurrencyInfo(name: 'Colombian Peso', code: 'COP', symbol: '\$', flag: '🇨🇴'),
  CurrencyInfo(name: 'Costa Rican Colón', code: 'CRC', symbol: '₡', flag: '🇨🇷'),
  CurrencyInfo(name: 'Cuban Peso', code: 'CUP', symbol: '\$', flag: '🇨🇺'),
  CurrencyInfo(name: 'Cape Verdean Escudo', code: 'CVE', symbol: 'Esc', flag: '🇨🇻'),
  CurrencyInfo(name: 'Czech Koruna', code: 'CZK', symbol: 'Kč', flag: '🇨🇿'),
  CurrencyInfo(name: 'Djiboutian Franc', code: 'DJF', symbol: 'Fdj', flag: '🇩🇯'),
  CurrencyInfo(name: 'Danish Krone', code: 'DKK', symbol: 'kr', flag: '🇩🇰'),
  CurrencyInfo(name: 'Dominican Peso', code: 'DOP', symbol: 'RD\$', flag: '🇩🇴'),
  CurrencyInfo(name: 'Algerian Dinar', code: 'DZD', symbol: 'د.ج', flag: '🇩🇿'),
  CurrencyInfo(name: 'Eritrean Nakfa', code: 'ERN', symbol: 'Nfk', flag: '🇪🇷'),
  CurrencyInfo(name: 'Ethiopian Birr', code: 'ETB', symbol: 'Br', flag: '🇪🇹'),
  CurrencyInfo(name: 'Fijian Dollar', code: 'FJD', symbol: 'FJ\$', flag: '🇫🇯'),
  CurrencyInfo(name: 'Falkland Islands Pound', code: 'FKP', symbol: '£', flag: '🇫🇰'),
  CurrencyInfo(name: 'Georgian Lari', code: 'GEL', symbol: '₾', flag: '🇬🇪'),
  CurrencyInfo(name: 'Ghanaian Cedi', code: 'GHS', symbol: 'GH₵', flag: '🇬🇭'),
  CurrencyInfo(name: 'Gibraltar Pound', code: 'GIP', symbol: '£', flag: '🇬🇮'),
  CurrencyInfo(name: 'Gambian Dalasi', code: 'GMD', symbol: 'D', flag: '🇬🇲'),
  CurrencyInfo(name: 'Guinean Franc', code: 'GNF', symbol: 'FG', flag: '🇬🇳'),
  CurrencyInfo(name: 'Guatemalan Quetzal', code: 'GTQ', symbol: 'Q', flag: '🇬🇹'),
  CurrencyInfo(name: 'Guyanese Dollar', code: 'GYD', symbol: 'GY\$', flag: '🇬🇾'),
  CurrencyInfo(name: 'Hong Kong Dollar', code: 'HKD', symbol: 'HK\$', flag: '🇭🇰'),
  CurrencyInfo(name: 'Honduran Lempira', code: 'HNL', symbol: 'L', flag: '🇭🇳'),
  CurrencyInfo(name: 'Croatian Kuna', code: 'HRK', symbol: 'kn', flag: '🇭🇷'),
  CurrencyInfo(name: 'Haitian Gourde', code: 'HTG', symbol: 'G', flag: '🇭🇹'),
  CurrencyInfo(name: 'Hungarian Forint', code: 'HUF', symbol: 'Ft', flag: '🇭🇺'),
  CurrencyInfo(name: 'Indonesian Rupiah', code: 'IDR', symbol: 'Rp', flag: '🇮🇩'),
  CurrencyInfo(name: 'Israeli Shekel', code: 'ILS', symbol: '₪', flag: '🇮🇱'),
  CurrencyInfo(name: 'Indian Rupee', code: 'INR', symbol: '₹', flag: '🇮🇳'),
  CurrencyInfo(name: 'Iraqi Dinar', code: 'IQD', symbol: 'ع.د', flag: '🇮🇶'),
  CurrencyInfo(name: 'Iranian Rial', code: 'IRR', symbol: '﷼', flag: '🇮🇷'),
  CurrencyInfo(name: 'Icelandic Króna', code: 'ISK', symbol: 'kr', flag: '🇮🇸'),
  CurrencyInfo(name: 'Jamaican Dollar', code: 'JMD', symbol: 'J\$', flag: '🇯🇲'),
  CurrencyInfo(name: 'Jordanian Dinar', code: 'JOD', symbol: 'د.ا', flag: '🇯🇴'),
  CurrencyInfo(name: 'Japanese Yen', code: 'JPY', symbol: '¥', flag: '🇯🇵'),
  CurrencyInfo(name: 'Kenyan Shilling', code: 'KES', symbol: 'KSh', flag: '🇰🇪'),
  CurrencyInfo(name: 'Kyrgyz Som', code: 'KGS', symbol: 'сом', flag: '🇰🇬'),
  CurrencyInfo(name: 'Cambodian Riel', code: 'KHR', symbol: '៛', flag: '🇰🇭'),
  CurrencyInfo(name: 'Comorian Franc', code: 'KMF', symbol: 'CF', flag: '🇰🇲'),
  CurrencyInfo(name: 'South Korean Won', code: 'KRW', symbol: '₩', flag: '🇰🇷'),
  CurrencyInfo(name: 'Kuwaiti Dinar', code: 'KWD', symbol: 'د.ك', flag: '🇰🇼'),
  CurrencyInfo(name: 'Cayman Islands Dollar', code: 'KYD', symbol: 'CI\$', flag: '🇰🇾'),
  CurrencyInfo(name: 'Kazakhstani Tenge', code: 'KZT', symbol: '₸', flag: '🇰🇿'),
  CurrencyInfo(name: 'Lao Kip', code: 'LAK', symbol: '₭', flag: '🇱🇦'),
  CurrencyInfo(name: 'Lebanese Pound', code: 'LBP', symbol: 'ل.ل', flag: '🇱🇧'),
  CurrencyInfo(name: 'Sri Lankan Rupee', code: 'LKR', symbol: 'Rs', flag: '🇱🇰'),
  CurrencyInfo(name: 'Liberian Dollar', code: 'LRD', symbol: 'L\$', flag: '🇱🇷'),
  CurrencyInfo(name: 'Lesotho Loti', code: 'LSL', symbol: 'L', flag: '🇱🇸'),
  CurrencyInfo(name: 'Libyan Dinar', code: 'LYD', symbol: 'ل.د', flag: '🇱🇾'),
  CurrencyInfo(name: 'Moroccan Dirham', code: 'MAD', symbol: 'د.م.', flag: '🇲🇦'),
  CurrencyInfo(name: 'Moldovan Leu', code: 'MDL', symbol: 'L', flag: '🇲🇩'),
  CurrencyInfo(name: 'Malagasy Ariary', code: 'MGA', symbol: 'Ar', flag: '🇲🇬'),
  CurrencyInfo(name: 'Macedonian Denar', code: 'MKD', symbol: 'ден', flag: '🇲🇰'),
  CurrencyInfo(name: 'Myanmar Kyat', code: 'MMK', symbol: 'K', flag: '🇲🇲'),
  CurrencyInfo(name: 'Mongolian Tögrög', code: 'MNT', symbol: '₮', flag: '🇲🇳'),
  CurrencyInfo(name: 'Macanese Pataca', code: 'MOP', symbol: 'MOP\$', flag: '🇲🇴'),
  CurrencyInfo(name: 'Mauritanian Ouguiya', code: 'MRU', symbol: 'UM', flag: '🇲🇷'),
  CurrencyInfo(name: 'Mauritian Rupee', code: 'MUR', symbol: '₨', flag: '🇲🇺'),
  CurrencyInfo(name: 'Maldivian Rufiyaa', code: 'MVR', symbol: 'Rf', flag: '🇲🇻'),
  CurrencyInfo(name: 'Malawian Kwacha', code: 'MWK', symbol: 'MK', flag: '🇲🇼'),
  CurrencyInfo(name: 'Mexican Peso', code: 'MXN', symbol: 'Mex\$', flag: '🇲🇽'),
  CurrencyInfo(name: 'Malaysian Ringgit', code: 'MYR', symbol: 'RM', flag: '🇲🇾'),
  CurrencyInfo(name: 'Mozambican Metical', code: 'MZN', symbol: 'MT', flag: '🇲🇿'),
  CurrencyInfo(name: 'Namibian Dollar', code: 'NAD', symbol: 'N\$', flag: '🇳🇦'),
  CurrencyInfo(name: 'Nigerian Naira', code: 'NGN', symbol: '₦', flag: '🇳🇬'),
  CurrencyInfo(name: 'Nicaraguan Córdoba', code: 'NIO', symbol: 'C\$', flag: '🇳🇮'),
  CurrencyInfo(name: 'Norwegian Krone', code: 'NOK', symbol: 'kr', flag: '🇳🇴'),
  CurrencyInfo(name: 'Nepalese Rupee', code: 'NPR', symbol: 'Rs', flag: '🇳🇵'),
  CurrencyInfo(name: 'New Zealand Dollar', code: 'NZD', symbol: 'NZ\$', flag: '🇳🇿'),
  CurrencyInfo(name: 'Omani Rial', code: 'OMR', symbol: 'ر.ع.', flag: '🇴🇲'),
  CurrencyInfo(name: 'Panamanian Balboa', code: 'PAB', symbol: 'B/.', flag: '🇵🇦'),
  CurrencyInfo(name: 'Peruvian Sol', code: 'PEN', symbol: 'S/.', flag: '🇵🇪'),
  CurrencyInfo(name: 'Papua New Guinean Kina', code: 'PGK', symbol: 'K', flag: '🇵🇬'),
  CurrencyInfo(name: 'Philippine Peso', code: 'PHP', symbol: '₱', flag: '🇵🇭'),
  CurrencyInfo(name: 'Pakistani Rupee', code: 'PKR', symbol: '₨', flag: '🇵🇰'),
  CurrencyInfo(name: 'Polish Złoty', code: 'PLN', symbol: 'zł', flag: '🇵🇱'),
  CurrencyInfo(name: 'Paraguayan Guaraní', code: 'PYG', symbol: '₲', flag: '🇵🇾'),
  CurrencyInfo(name: 'Qatari Riyal', code: 'QAR', symbol: 'ر.ق', flag: '🇶🇦'),
  CurrencyInfo(name: 'Romanian Leu', code: 'RON', symbol: 'lei', flag: '🇷🇴'),
  CurrencyInfo(name: 'Serbian Dinar', code: 'RSD', symbol: 'din.', flag: '🇷🇸'),
  CurrencyInfo(name: 'Russian Ruble', code: 'RUB', symbol: '₽', flag: '🇷🇺'),
  CurrencyInfo(name: 'Rwandan Franc', code: 'RWF', symbol: 'RF', flag: '🇷🇼'),
  CurrencyInfo(name: 'Sudanese Pound', code: 'SDG', symbol: 'ج.س.', flag: '🇸🇩'),
  CurrencyInfo(name: 'Swedish Krona', code: 'SEK', symbol: 'kr', flag: '🇸🇪'),
  CurrencyInfo(name: 'Singapore Dollar', code: 'SGD', symbol: 'S\$', flag: '🇸🇬'),
  CurrencyInfo(name: 'Saint Helena Pound', code: 'SHP', symbol: '£', flag: '🇸🇭'),
  CurrencyInfo(name: 'Sierra Leonean Leone', code: 'SLE', symbol: 'Le', flag: '🇸🇱'),
  CurrencyInfo(name: 'Somali Shilling', code: 'SOS', symbol: 'Sh', flag: '🇸🇴'),
  CurrencyInfo(name: 'Surinamese Dollar', code: 'SRD', symbol: 'Sr\$', flag: '🇸🇷'),
  CurrencyInfo(name: 'South Sudanese Pound', code: 'SSP', symbol: '£', flag: '🇸🇸'),
  CurrencyInfo(name: 'São Tomé Dobra', code: 'STN', symbol: 'Db', flag: '🇸🇹'),
  CurrencyInfo(name: 'Syrian Pound', code: 'SYP', symbol: '£S', flag: '🇸🇾'),
  CurrencyInfo(name: 'Swazi Lilangeni', code: 'SZL', symbol: 'E', flag: '🇸🇿'),
  CurrencyInfo(name: 'Thai Baht', code: 'THB', symbol: '฿', flag: '🇹🇭'),
  CurrencyInfo(name: 'Tajikistani Somoni', code: 'TJS', symbol: 'SM', flag: '🇹🇯'),
  CurrencyInfo(name: 'Turkmen Manat', code: 'TMT', symbol: 'T', flag: '🇹🇲'),
  CurrencyInfo(name: 'Tunisian Dinar', code: 'TND', symbol: 'د.ت', flag: '🇹🇳'),
  CurrencyInfo(name: "Tongan Pa'anga", code: 'TOP', symbol: 'T\$', flag: '🇹🇴'),
  CurrencyInfo(name: 'Turkish Lira', code: 'TRY', symbol: '₺', flag: '🇹🇷'),
  CurrencyInfo(name: 'Trinidad & Tobago Dollar', code: 'TTD', symbol: 'TT\$', flag: '🇹🇹'),
  CurrencyInfo(name: 'New Taiwan Dollar', code: 'TWD', symbol: 'NT\$', flag: '🇹🇼'),
  CurrencyInfo(name: 'Tanzanian Shilling', code: 'TZS', symbol: 'TSh', flag: '🇹🇿'),
  CurrencyInfo(name: 'Ukrainian Hryvnia', code: 'UAH', symbol: '₴', flag: '🇺🇦'),
  CurrencyInfo(name: 'Ugandan Shilling', code: 'UGX', symbol: 'USh', flag: '🇺🇬'),
  CurrencyInfo(name: 'Uruguayan Peso', code: 'UYU', symbol: '\$U', flag: '🇺🇾'),
  CurrencyInfo(name: 'Uzbekistani Som', code: 'UZS', symbol: "so'm", flag: '🇺🇿'),
  CurrencyInfo(name: 'Venezuelan Bolívar', code: 'VES', symbol: 'Bs.S', flag: '🇻🇪'),
  CurrencyInfo(name: 'Vietnamese Đồng', code: 'VND', symbol: '₫', flag: '🇻🇳'),
  CurrencyInfo(name: 'Vanuatu Vatu', code: 'VUV', symbol: 'VT', flag: '🇻🇺'),
  CurrencyInfo(name: 'Samoan Tālā', code: 'WST', symbol: 'WS\$', flag: '🇼🇸'),
  CurrencyInfo(name: 'Central African CFA Franc', code: 'XAF', symbol: 'FCFA', flag: '🌍'),
  CurrencyInfo(name: 'East Caribbean Dollar', code: 'XCD', symbol: 'EC\$', flag: '🌎'),
  CurrencyInfo(name: 'West African CFA Franc', code: 'XOF', symbol: 'CFA', flag: '🌍'),
  CurrencyInfo(name: 'CFP Franc', code: 'XPF', symbol: '₣', flag: '🌏'),
  CurrencyInfo(name: 'Yemeni Rial', code: 'YER', symbol: '﷼', flag: '🇾🇪'),
  CurrencyInfo(name: 'South African Rand', code: 'ZAR', symbol: 'R', flag: '🇿🇦'),
  CurrencyInfo(name: 'Zambian Kwacha', code: 'ZMW', symbol: 'ZK', flag: '🇿🇲'),
  CurrencyInfo(name: 'Zimbabwean Dollar', code: 'ZWL', symbol: 'Z\$', flag: '🇿🇼'),
  CurrencyInfo(name: 'North Korean Won', code: 'KPW', symbol: '₩', flag: '🇰🇵'),
];
